import {useMemo,useState} from 'react';
import {calcBeam,BeamInput} from './engine/beam';
import {concretes,steels} from './engine/materials';

type Module='Dầm'|'Cột'|'Sàn'|'Móng';
const modules:Module[]=['Dầm','Cột','Sàn','Móng'];
export default function App(){
 const [module,setModule]=useState<Module>('Dầm');
 const [x,setX]=useState<BeamInput>({b:300,h:500,a:40,M:100,Q:80,concrete:'B25',steel:'CB400-V',AsProvided:1200});
 const r=useMemo(()=>calcBeam(x),[x]);
 const set=(k:keyof BeamInput,v:string)=>setX(p=>({...p,[k]:['b','h','a','M','Q','AsProvided'].includes(k)?Number(v):v} as BeamInput));
 return <div className="app"><aside><div className="brand">BTCT <span>5574</span></div><p className="muted">ENGINE TÍNH TOÁN</p>{modules.map(m=><button className={module===m?'nav active':'nav'} onClick={()=>setModule(m)} key={m}>▣&nbsp; {m} BTCT</button>)}<div className="sidefoot">v0.1 • Khung nền tảng</div></aside><main><header><div><h1>Hệ thống Kết cấu BTCT</h1><p>Thiết kế theo kiến trúc engine dùng chung • Module {module}</p></div><button className="outline" onClick={()=>window.print()}>Xuất / In PDF</button></header><section className="notice">⚠ Công cụ hỗ trợ kỹ sư. Công thức sẽ được khóa phiên bản sau khi đối chiếu workbook và Golden Cases.</section><div className="grid"><section className="card"><h2>Thông số tính toán</h2><div className="form"><label>b <input type="number" value={x.b} onChange={e=>set('b',e.target.value)}/> mm</label><label>h <input type="number" value={x.h} onChange={e=>set('h',e.target.value)}/> mm</label><label>a <input type="number" value={x.a} onChange={e=>set('a',e.target.value)}/> mm</label><label>M <input type="number" value={x.M} onChange={e=>set('M',e.target.value)}/> kNm</label><label>Q <input type="number" value={x.Q} onChange={e=>set('Q',e.target.value)}/> kN</label><label>As bố trí <input type="number" value={x.AsProvided} onChange={e=>set('AsProvided',e.target.value)}/> mm²</label><label>Bê tông<select value={x.concrete} onChange={e=>set('concrete',e.target.value)}>{concretes.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Thép dọc<select value={x.steel} onChange={e=>set('steel',e.target.value)}>{steels.map(s=><option key={s.name}>{s.name}</option>)}</select></label></div></section><section className="card"><h2>Kết quả kiểm tra</h2><Result name="Chiều cao làm việc ho" value={`${r.ho.toFixed(1)} mm`} /><Result name="αm" value={r.alphaM.toFixed(4)} /><Result name="ξ / ξR" value={`${r.xi.toFixed(4)} / ${r.xiR.toFixed(4)}`} /><Result name="As yêu cầu" value={`${r.AsRequired.toFixed(0)} mm²`} /><Result name="Hàm lượng μ" value={`${r.mu.toFixed(2)} %`} /><Result name="Uốn" value={r.flexure?'ĐẠT':'KHÔNG ĐẠT'} ok={r.flexure}/><Result name="Cắt: Q / Qbt" value={`${Math.abs(x.Q).toFixed(1)} / ${r.Qbt.toFixed(1)} kN`} /><Result name="Cắt" value={r.shear?'ĐẠT':'KHÔNG ĐẠT'} ok={r.shear}/></section></div><section className="roadmap card"><h2>Lộ trình hệ thống</h2><div className="steps"><b>01<br/><span>Engine chung</span></b><b>02<br/><span>Dầm</span></b><b>03<br/><span>Cột</span></b><b>04<br/><span>Sàn</span></b><b>05<br/><span>Móng</span></b><b>06<br/><span>Excel / PDF</span></b><b>07<br/><span>Golden Cases</span></b></div></section></main></div>
}
function Result({name,value,ok}:{name:string,value:string,ok?:boolean}){return <div className="result"><span>{name}</span><strong className={ok===undefined?'':ok?'ok':'bad'}>{value}</strong></div>}
